### ISSUE TITLE
Trouble installing latest version

### ISSUE THREAD

**Issue by jlarmstrongiv** [swzzl-com/bookiza.cli#6]
Thanks for getting back to me!  My email bounced, so I figured it’d be easier to make an issue here.  

# Installing Attempts
I checked the version of bookiza that I installed from npm, and it was, indeed, out of date.  

## Installing with NPM from Github 
I tried npm installing from the github URL, I received the following errors when making a sample book from scratch (the bookiza -v reported:  1.0.0-semver-ized):  

`bookiza new MY-AWESOME-BOOK-V3 --leafs 12 --template comics`

`Initializing…  [ manuscript=MY-AWESOME-BOOK-V3 | leafs=12 | template=comics ]
Copying crust failed Error: ENOENT: no such file or directory, lstat '/usr/local/lib/node_modules/bookiza/crust'
Failed to create subdirectories… Error: EEXIST: file already exists, mkdir 'assets/css'
License.txt… :added.
.gitignoring /build /node_modules… :done.
README initialization… :success.
Applying a comics layout… :success.
Arcvalues & Package Json unavailable Error: Did not find the arc!
Failed. Gulpfile unavailable. Error: ENOENT: no such file or directory, link 'crust/gulpfile.js' -> 'gulpfile.js'`

## Installing GitHub master downloaded as a local package with npm
I downloaded the bookiza zip from github and npm installed it locally, after which I replaced the alias in my global modules with the unzipped folder (the bookiza -v reported:  1.0.0-semver-ized).  Unfortunately, I still had this error when creating a new book:  

`bookiza new MY-AWESOME-BOOK-V6 --leafs 12 --template comics`

`Initializing…  [ manuscript=MY-AWESOME-BOOK-V6 | leafs=12 | template=comics ]
.gitignoring /build /node_modules… :done.
README initialization… :success.
License.txt… :added.
Applying a comics layout… :success.
Mobilizing crust… :success.
Arcvalues & Package Json unavailable Error: Did not find the arc!
Server setup… :complete.`

## Other Troubleshooting
Unfortunately, the bookiza server fails to run.  Then, I realized that it didn’t actually create any pages (even though 12 was specified when creating it).  

I tried adding pages, but it threw an error requiring a .bookrc file.  I was able to add and configure the file, but bookiza server still failed.  After comparing my generated booklet to the bookiza framework example, I realized I did not have a package json in my root (and thus no node modules), and that my crust folder was completely empty.  And then I gave up debugging.

# Other Questions
Looking at the .bookrc example in the readme, I was just wondering what other options are available.  

Would the below json be valid?  What exactly is the HEAD key and what does it do?  What other options are there for HTML, CSS, JS, and HEAD?

`{
  "mode": {
    "HTML": "markdown", 
    "CSS": "scss",
    "JS": "babel",
    "HEAD": "html"
  }
}`

Similarly, how do templates work?

What does command bookiza push do, and how is it compare to bookiza publish and bookiza server?

I’m glad the page proportions are so close.  That’ll help a bunch.  Resizing 40 * 6 pages would not be fun.  Unfortunately, the magazine I’m working is not on github nor open source.  I’d have to get the school’s permission after summer ends.  I’ll try again to get it working.

**Comment by marvindanig** [comment]
1. Please try again with `$ npm i -g bookiza@1.0.0-beta.0`. Try with `sudo` if it doesn't work in the first pass. We're using mac/node@10.x, so YMMV depending on OS/node. 

In any case LMK how it goes for you. ✨

For the question on templates you may want to look at the following example of `.bookrc` that uses `haml` for HTML templating: https://github.com/marvindanig/bookiza-framework
