### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by triptych** [swzzl-com/bookiza.cli#7]
You say your MIT license is "dormant" and real license is TBD. It makes it really hard to consider investing time in all this tech when the licensing is up in the air.

**Comment by marvindanig** [comment]
MIT License will probably be an option as soon as we have the first cut ready. It is dormant because I am undecided about its usefulness in 2019.

**Comment by marvindanig** [comment]
Will take into account the following: 

https://techcrunch.com/2019/05/30/lack-of-leadership-in-open-source-results-in-source-available-licenses/ 

…and following:

https://news.ycombinator.com/item?id=20070507

**Comment by marvindanig** [comment]
We have decided to adopt a [Democratic Open Source License](https://bubblin.io/bookiza/docs/license) for free usage of Bookiza whereas the commercial options will follow on later.
